skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
liquidity_aware_lending = "6HxjRZGNXgKE21WRsd5RbwXJGmNCcQrpEJ1uzBnBJ8M6"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
